"""
UI Constants for 5GH'z Cleaner
Color scheme and configuration values
"""

# Window Configuration
WINDOW_WIDTH = 900
WINDOW_HEIGHT = 1019
WINDOW_MIN_WIDTH = 876
WINDOW_MIN_HEIGHT = 1019

# Color Scheme
BG_MAIN = "#0d1b2a"
BG_SECONDARY = "#1b263b"
ACCENT_COLOR = "#e0e1dd"
FG_MAIN = "#778da9"
FG_SECONDARY = "#e0e1dd"
SHADOW_COLOR = "#2a3342"
BLUE_ACCENT = "#4a9eff"
WARNING_COLOR = "#ff9500"

# Animation Timings
FADE_DURATION = 300
BUTTON_PRESS_DURATION = 100
SHIELD_GLOW_DURATION = 1500
SHIELD_PULSE_INTERVAL = 2.0

# Shadow Configuration
SHADOW_BLUR_RADIUS = 8
SHADOW_OPACITY = 0.2
GLOW_BLUR_MIN = 12
GLOW_BLUR_MAX = 15
GLOW_OPACITY_MIN = 0.15
GLOW_OPACITY_MAX = 0.25
