name: Security Audit

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    # Exécuter tous les lundis à 9h
    - cron: '0 9 * * 1'

jobs:
  security-audit:
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pylint
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
    
    - name: Run Bandit (Security Linter)
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . -f txt
      continue-on-error: true
    
    - name: Run Safety (Dependency Check)
      run: |
        safety check --json > safety-report.json || true
        safety check
      continue-on-error: true
    
    - name: Run Pylint (Code Quality)
      run: |
        Get-ChildItem -Recurse -Filter *.py | ForEach-Object { pylint $_.FullName --output-format=text } > pylint-report.txt
        Get-ChildItem -Recurse -Filter *.py | ForEach-Object { pylint $_.FullName --output-format=colorized }
      continue-on-error: true
      shell: pwsh
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          pylint-report.txt
      if: always()
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"
